"""
=========================================================
Project : Sridevi Enterprises
File    : department_keywords.py
Purpose : Department keyword mappings.

Author  : Srikar
=========================================================
"""

DEPARTMENT_KEYWORDS = {
    "Furniture": [
        "chair",
        "stool",
        "table",
        "desk",
        "almirah",
        "cabinet",
        "rack",
        "shelf",
        "cot",
        "bed",
        "sofa",
        "bench",
        "locker",
        "drawer",
        "podium",
        "dining",
        "study",
        "meeting",
        "counter",
    ],
    "Home Appliances": [
        "fan",
        "cooler",
        "geyser",
        "kettle",
        "vacuum",
        "purifier",
        "mixer",
        "grinder",
        "refrigerator",
        "washing",
        "iron",
        "microwave",
        "heater",
        "flask",
    ],
    "Electronics": [
        "tv",
        "television",
        "speaker",
        "camera",
        "cctv",
        "scanner",
        "display",
        "projector",
        "watch",
        "clock",
        "recorder",
        "amplifier",
    ],
    "Computer & IT": [
        "computer",
        "laptop",
        "monitor",
        "keyboard",
        "mouse",
        "printer",
        "motherboard",
        "processor",
        "ssd",
        "hard disk",
        "ram",
        "software",
        "operating system",
        "pdf",
        "network",
        "router",
        "switch",
        "barcode",
        "label printer",
    ],
    "Electrical": [
        "battery",
        "cable",
        "wire",
        "adapter",
        "power",
        "led",
        "lighting",
        "multimeter",
        "switch",
        "plug",
        "socket",
        "ups",
        "inverter",
        "charger",
    ],
    "Office Supplies": [
        "paper",
        "pen",
        "planner",
        "toner",
        "ribbon",
        "bag",
        "file",
        "stationery",
        "sticker",
        "label",
        "passport",
        "bankbook",
    ],
    "Kitchen & Dining": [
        "spoon",
        "plate",
        "bowl",
        "jug",
        "tea",
        "dinner",
        "chimta",
        "masala",
        "cooker",
        "stove",
    ],
    "Sports & Fitness": ["yoga", "sports"],
    "Safety & Industrial": [
        "helmet",
        "ladder",
        "plier",
        "tool",
        "barrier",
        "glove",
        "safety",
        "fire",
    ],
    "Miscellaneous": [],
}
